[package]
name    = "nvman"
version = "2.1.0"
authors = ["Kevin <quebin31@gmail.com>"]
edition = "2018"

[dependencies]
users     = "0.9"
shells    = "0.2.0"
ansi_term = "0.11.0"

[dependencies.io]
version = "0.1.7"
package = "text_io"
